# The following code demonstrates the problem

In [1]:
import io
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [26]:
filename = "f:\\CloudStation\\TournamentProject\\RegExport_CoTourn_2018-03-15sample.csv"
filebuffer = io.open(filename,'r',encoding='utf-8')

In [27]:
raw_df=pd.read_csv(filebuffer)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 15369: invalid start byte

# to fix the problem let's filter out any garbage characters

## first let's see what garbage we can see by looking for anything bigger than 0x7f

In [79]:
filename = "f:\\CloudStation\\TournamentProject\\RegExport_CoTourn_2018-03-15sample.csv"
with open(filename, 'r+b') as f:
    while True:
        b=f.read(1)
        if not b:
            break
        if( b > b'\x7f'):
            s=b.decode('iso8859_3')
            print("{} {}".format(b,s))

b'\x92' 
b'\x94' 
b'\x92' 
b'\x92' 
b'\xe9' é
b'\x94' 

## next let's re-write the bytes with a '#' or '\x23' 
- notice we're going to change the filename to avoid whacking the orginal

In [83]:
import shutil
shutil.copy("f:\\CloudStation\\TournamentProject\\RegExport_CoTourn_2018-03-15sample.csv","f:\\CloudStation\\TournamentProject\\HasJunkInIt.csv")
filename = "f:\\CloudStation\\TournamentProject\\HasJunkInIt.csv"
print("Cleaning out bad bytes")
with open(filename, 'r+b') as f:
    while True:
        b=f.read(1)
        if not b:
            break
        if( b > b'\x7f'):
            s=b.decode('iso8859_3')
            print("{} {}".format(b,s))
            b=b'\x23'
            f.seek(-1,1)
            f.write(b)
 
print("There should not be any bad bytes left")
with open(filename, 'r+b') as f:
    while True:
        b=f.read(1)
        if not b:
            break
        if( b > b'\x7f'):
            s=b.decode('iso8859_3')
            print("{} {}".format(b,s))
            
print("now read it as a dataframe")            
filebuffer = io.open(filename,'r',encoding='utf-8')
raw_df=pd.read_csv(filebuffer)
print(raw_df)
filebuffer.close()

Cleaning out bad bytes
b'\x92' 
b'\x94' 
b'\x92' 
b'\x92' 
b'\xe9' é
b'\x94' 
There should not be any bad bytes left
now read it as a dataframe
    Event Date  Registrant ID First Name    Last Name  Gender  \
0    4/21/2018        1393542      Caleb       Keener    Male
1    4/21/2018        1389599        Ria        Jones  Female
2    4/21/2018        1386347      Jason      Stelley    Male
3    4/21/2018        1386190     Dasodo        Ramos    Male
4    4/21/2018        1382147      Brock         Rice    Male
5    4/21/2018        1381558     Donald   Burkhalter    Male
6    4/21/2018        1380988     Payten        Clark  Female
7    4/21/2018        1379222  Stephanie      Cameron  Female
8    4/21/2018        1375247      Henry    Dickinson    Male
9    4/21/2018        1375222    Michael      Shelton    Male
10   4/21/2018        1394192    Micheal        Ervin    Male
11   4/21/2018        1394191     Arlene        Ervin  Female
12   4/21/2018        1381631       Kula     Tanuvasa    Male
13   4/21/2018        1380975     Helena         Blan  Female
14   4/21/2018        1375184   Samantha      Scheele  Female
15   4/21/2018        1391618       Alex    Reinacher    Male
16   4/21/2018        1390472       Alex   Gottschalk    Male
17   4/21/2018        1390345       Luke       Jassem    Male
18   4/21/2018        1390252      Wyatt        Green    Male
19   4/21/2018        1388731     Ashley      Maxwell  Female
20   4/21/2018        1388730      Jakob      Maxwell    Male
21   4/21/2018        1388729       Beth      Maxwell  Female
22   4/21/2018        1388566   Margaret      Buttery  Female
23   4/21/2018        1388565      Marie     Ciminski  Female
24   4/21/2018        1388564  Genevieve     Ciminski  Female
25   4/21/2018        1388307    Rebecca    Rasmussen  Female
26   4/21/2018        1387792       Leah     Leverich  Female
27   4/21/2018        1386151    Madison   Villagomez  Female
28   4/21/2018        1386150   Nicholas   Villagomez    Male
29   4/21/2018        1385897     Sophia      Hopwood  Female
..         ...            ...        ...          ...     ...
225  4/21/2018        1386131       Liam    Robertson    Male
226  4/21/2018        1386101     Chance      Fischer    Male
227  4/21/2018        1385206    Preston  Rittenhouse    Male
228  4/21/2018        1384118      Maddi         Gude  Female
229  4/21/2018        1383455  Alexandra        Terry  Female
230  4/21/2018        1382286   Nicholas      Machado    Male
231  4/21/2018        1382241      Jaime        Klein  Female
232  4/21/2018        1382240    Braiden        Klein    Male
233  4/21/2018        1382226    Brandon        Hoang    Male
234  4/21/2018        1382225         DJ        Hoang    Male
235  4/21/2018        1381576        Sam       Thorne    Male
236  4/21/2018        1381514     Landon   Hornbacher    Male
237  4/21/2018        1380198    Shannon       Spence  Female
238  4/21/2018        1380197      CHRIS       SPENCE    Male
239  4/21/2018        1379979      Logan      Garneau  Female
240  4/21/2018        1379972      Sahil       Balani    Male
241  4/21/2018        1379149      Katie      Whitner  Female
242  4/21/2018        1379009     Felipe         Neri    Male
243  4/21/2018        1378859      Sarah     Chuapoco  Female
244  4/21/2018        1378858    Trinity     Chuapoco  Female
245  4/21/2018        1378857    Anthony     Chuapoco    Male
246  4/21/2018        1378771       Drew       Turner    Male
247  4/21/2018        1378682    Cameron   Chatterley    Male
248  4/21/2018        1376411      Jaden       Muscat    Male
249  4/21/2018        1375230      Molly   Houtkooper  Female
250  4/21/2018        1375229       Paul   Houtkooper    Male
251  4/21/2018        1389702      Alice       Harada  Female
252  4/21/2018        1389701    Jackson       Harada    Male
253  4/21/2018        1380028       Kiki        Clark  Female
254  4/21/2018        1380002     Edward    Henderson    Male

    Select Your Z Ultimate Studio Out of State Studio Name  Competitor's Age?  \
0                      CO- Arvada                      NaN                  7
1                      CO- Arvada                      NaN                 28
2                      CO- Arvada                      NaN                 44
3                      CO- Arvada                      NaN                  5
4                      CO- Arvada                 Colorado                  8
5                      CO- Arvada                      NaN                  8
6                      CO- Arvada                      NaN                 12
7                      CO- Arvada                      NaN                 12
8                      CO- Arvada                      NaN                 11
9                      CO- Arvada                      NaN                  8
10                     CO- Aurora                      NaN                 47
11                     CO- Aurora                      NaN                 44
12                     CO- Aurora                      NaN                  7
13                     CO- Aurora                      NaN                  6
14                     CO- Aurora                      NaN                 16
15                 CO- Broomfield                      NaN                  9
16                 CO- Broomfield                      NaN                 13
17                 CO- Broomfield                      NaN                  8
18                 CO- Broomfield                 Colorado                 15
19                 CO- Broomfield                      NaN                  6
20                 CO- Broomfield                      NaN                  7
21                 CO- Broomfield                      NaN                 36
22                 CO- Broomfield                       CO                 49
23                 CO- Broomfield                       CO                 13
24                 CO- Broomfield                       CO                  5
25                 CO- Broomfield                       CO                 36
26                 CO- Broomfield                       CO                 36
27                 CO- Broomfield                      NaN                 11
28                 CO- Broomfield                      NaN                 13
29                 CO- Broomfield                      NaN                 10
..                            ...                      ...                ...
225                CO- Smoky Hill                      NaN                  6
226                CO- Smoky Hill                 Colorado                  4
227                CO- Smoky Hill                       CO                  9
228                CO- Smoky Hill                      NaN                 12
229                CO- Smoky Hill                 Colorado                  7
230                CO- Smoky Hill                 Colorado                  6
231                CO- Smoky Hill                      NaN                 41
232                CO- Smoky Hill                 Colorado                 13
233                CO- Smoky Hill                 Colorado                  7
234                CO- Smoky Hill                 Colorado                  9
235                CO- Smoky Hill                 Colorado                  7
236                CO- Smoky Hill                      NaN                  6
237                CO- Smoky Hill                       CO                 43
238                CO- Smoky Hill                 Colorado                 43
239                CO- Smoky Hill                      NaN                  8
240                CO- Smoky Hill                      NaN                  9
241                CO- Smoky Hill                      NaN                  9
242                CO- Smoky Hill                       CO                  8
243                CO- Smoky Hill                      NaN                  7
244                CO- Smoky Hill            CO - Colorado                 11
245                CO- Smoky Hill            CO - Colorado                 13
246                CO- Smoky Hill                      NaN                 47
247                CO- Smoky Hill                       CO                  8
248                CO- Smoky Hill                      NaN                  7
249                CO- Smoky Hill                      NaN                 12
250                CO- Smoky Hill                      NaN                 43
251               CO- West Arvada                       CO                  6
252               CO- West Arvada                       CO                 13
253                  Out of State        Pacific Palisades                 14
254                  Out of State           MN - Richfield                 31

    Competitor's Weight (e.g. 73lbs.)?  \
0                               50 lbs
1                                  130
2                                  190
3                                   40
4                                65lbs
5                                   78
6                                  123
7                                  110
8                                  110
9                                   68
10                              230lbs
11                              150lbs
12                               64lbs
13                                  45
14                                 115
15                                  69
16                                 123
17                              54 lbs
18                                 186
19                                  39
20                                  53
21                                 133
22                                 135
23                                 125
24                                  38
25                                 165
26                                 150
27                             94 lbs.
28                               97lbs
29                                  58
..                                 ...
225                                 51
226                                 45
227                            56 lbs.
228                            144 lbs
229                                 70
230                                 60
231                                119
232                                 84
233                                 40
234                                 55
235                                 69
236                                 51
237                                115
238                                210
239                                 73
240                                 50
241                                70#
242                             60 lbs
243                             46 lbs
244                             98 lbs
245                            103 lbs
246                                210
247                              68lbs
248                              51lbs
249                                 90
250                                200
251                                 45
252                                 80
253                            104lbs.
254                                270

    Competitor's Height (e.g. 4 ft. 2 in. )?  \
0                                  4 ft, 1in
1                                       5'8"
2                                 5ft. 11in.
3                                  3 ft 3 in
4                                      4 ft.
5                                    4ft 4in
6                                       4'9"
7                                   5ft 3in.
8                                       5'4"
9                                       4"3"
10                                 6 ft 2 in
11                                  5 ft 2in
12                               4 ft. 3 in.
13                                       4ft
14                                   5ft 6in
15                                 4 ft 6 in
16                                      5'5"
17                               4 ft. 1 in.
18                                      5'7"
19                                      42in
20                                      50in
21                                   5ft 2in
22                                  5 ft 3in
23                           5 feet 4 inches
24                           3 feet 5 inches
25                                   5ft 5in
26                                       5.7
27                                 4ft. 7in.
28                               5 ft. 4 in.
29                                   4ft 5in
..                                       ...
225                                     3'6"
226                                     3'1"
227                            4 ft. 3.5 in.
228                             5 ft. 6.5 in
229                                      45"
230                                     4'5"
231                                5 ft 0 in
232                                5 ft 2 in
233                                    3'11"
234                                     4'2"
235                                     4'2"
236                                    3'11"
237                                     5'2"
238                                    5'10"
239                                     4'2"
240                                     4'1"
241                                      55#
242                              4 ft. 3 in.
243                                   3' 11"
244                                 4' 10.5"
245                                  5' 3.5"
246                                       6'
247                                 4ft 6in.
248                              4 ft. 2 in.
249                                     5 ft
250                                  5ft 8in
251                                3 ft 8 in
252                                     5 ft
253                                5ft. 1in.
254                               5 ft 10 in

    Choose The Division Based On Age?     Current Belt Rank?  \
0                         Youth (7-8)                  White
1                 Men & Women (18-39)       Brown 1st Degree
2        Senior Men & Women (40 & up)  Black Belt 2nd Degree
3                          Kids (4-6)                 Yellow
4                         Youth (7-8)                 Purple
5                         Youth (7-8)                 Purple
6                       Teens (12-14)                 Purple
7                       Teens (12-14)                   Blue
8                 Boys & Girls (9-11)         Green w/Stripe
9                         Youth (7-8)                 Purple
10       Senior Men & Women (40 & up)          Blue w/Stripe
11       Senior Men & Women (40 & up)                 Yellow
12                        Youth (7-8)                 Purple
13                         Kids (4-6)                 Orange
14               Young Adults (15-17)  Black Belt 1st Degree
15                Boys & Girls (9-11)                 Purple
16                      Teens (12-14)         Green w/Stripe
17                        Youth (7-8)         Green w/Stripe
18               Young Adults (15-17)          Blue w/Stripe
19                         Kids (4-6)                 Purple
20                        Youth (7-8)                   Blue
21                Men & Women (18-39)                   Blue
22       Senior Men & Women (40 & up)  Black Belt 1st Degree
23                      Teens (12-14)         Green w/Stripe
24                         Kids (4-6)                 Yellow
25                Men & Women (18-39)         Green w/Stripe
26                Men & Women (18-39)                   Blue
27                Boys & Girls (9-11)       Brown 1st Degree
28                      Teens (12-14)       Brown 1st Degree
29                Boys & Girls (9-11)          Blue w/Stripe
..                                ...                    ...
225                        Kids (4-6)                 Orange
226                        Kids (4-6)                 Yellow
227               Boys & Girls (9-11)                 Purple
228                     Teens (12-14)          Blue w/Stripe
229                       Youth (7-8)                 Yellow
230                        Kids (4-6)                 Orange
231      Senior Men & Women (40 & up)                  Green
232                     Teens (12-14)       Brown 3rd Degree
233                       Youth (7-8)                 Orange
234               Boys & Girls (9-11)       Brown 3rd Degree
235                       Youth (7-8)                   Blue
236                        Kids (4-6)                 Orange
237      Senior Men & Women (40 & up)                  Green
238      Senior Men & Women (40 & up)  Black Belt 1st Degree
239                       Youth (7-8)                 Yellow
240               Boys & Girls (9-11)                 Yellow
241               Boys & Girls (9-11)                 Yellow
242                       Youth (7-8)          Blue w/Stripe
243                       Youth (7-8)                   Blue
244               Boys & Girls (9-11)          Blue w/Stripe
245                     Teens (12-14)      Black Belt Junior
246      Senior Men & Women (40 & up)  Black Belt 1st Degree
247                       Youth (7-8)         Green w/Stripe
248                       Youth (7-8)                 Orange
249                     Teens (12-14)      Black Belt Junior
250      Senior Men & Women (40 & up)  Black Belt 1st Degree
251                        Kids (4-6)                  White
252                     Teens (12-14)       Brown 2nd Degree
253                     Teens (12-14)                 Purple
254               Men & Women (18-39)                 Purple

       Choose Forms, Sparring or Both. Choose Weapons.  \
0    2 Events - Forms & Sparring ($75)            None
1    2 Events - Forms & Sparring ($75)            None
2    2 Events - Forms & Sparring ($75)   Weapons ($35)
3                1 Event - Forms ($75)            None
4    2 Events - Forms & Sparring ($75)            None
5    2 Events - Forms & Sparring ($75)            None
6    2 Events - Forms & Sparring ($75)            None
7    2 Events - Forms & Sparring ($75)   Weapons ($35)
8    2 Events - Forms & Sparring ($75)   Weapons ($35)
9    2 Events - Forms & Sparring ($75)            None
10   2 Events - Forms & Sparring ($75)            None
11   2 Events - Forms & Sparring ($75)            None
12   2 Events - Forms & Sparring ($75)            None
13   2 Events - Forms & Sparring ($75)            None
14   2 Events - Forms & Sparring ($75)   Weapons ($35)
15   2 Events - Forms & Sparring ($75)            None
16   2 Events - Forms & Sparring ($75)            None
17   2 Events - Forms & Sparring ($75)            None
18               1 Event - Forms ($75)   Weapons ($35)
19   2 Events - Forms & Sparring ($75)            None
20   2 Events - Forms & Sparring ($75)            None
21   2 Events - Forms & Sparring ($75)            None
22   2 Events - Forms & Sparring ($75)            None
23   2 Events - Forms & Sparring ($75)            None
24   2 Events - Forms & Sparring ($75)            None
25                                None   Weapons ($35)
26   2 Events - Forms & Sparring ($75)            None
27               1 Event - Forms ($75)   Weapons ($35)
28   2 Events - Forms & Sparring ($75)   Weapons ($35)
29   2 Events - Forms & Sparring ($75)            None
..                                 ...             ...
225  2 Events - Forms & Sparring ($75)            None
226  2 Events - Forms & Sparring ($75)            None
227  2 Events - Forms & Sparring ($75)   Weapons ($35)
228  2 Events - Forms & Sparring ($75)            None
229  2 Events - Forms & Sparring ($75)            None
230  2 Events - Forms & Sparring ($75)            None
231  2 Events - Forms & Sparring ($75)            None